dubbo:
  application:
    name: view-facade
  registry:
    address: zookeeper://192.168.140.129:2181
  protocol:
    port: 20881
server:
  port: 9091

mybatis:
  mapper-locations: classpath:META-INF/mapper/*.xml

spring:
  #数据库信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_data_view?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
    username: root
    password: 7901
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.140.129
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 4
    cluster:
        nodes: 192.168.140.129:7001,192.168.140.129:7002,192.168.140.129:7003

